spring:
  kafka:
    consumer:
      group-id: "test-group"
      bootstrap-servers: "127.0.0.1:9092"
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 1
      isolation-level: read_committed
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

kafka:
  consumer:
    bootstrap-servers: "127.0.0.1:9092"
    error-topic-name: "shipment-sink-error"
    topic-name: "shipment-service"
    group-id: "consumer-id-1"
    spring-json-trusted-packages: "*"
    max-poll-records: "1"
    key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    security-protocol: SASL_SSL
    sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CCLOUD_API_KEY}" password="${CCLOUD_API_SECRET}";
    ssl-endpoint-identification-algorithm: https
    sasl-mechanism: PLAIN

lambda:
  function-name: "shipment-process-dev-index"
  region: "eu-west-2"

endpoints.jmx.enabled: true
spring.jmx.enabled: true

metrics.kafka:
  consumer.enabled: true
  producer.enabled: true