spring:
  json:
    use.type.headers: false
  kafka:
    consumer:
      group-id: "error-topic-drain-consumer-group"
      bootstrap-servers: "127.0.0.1:9092"
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 1
      isolation-level: read_committed
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      security-protocol: SASL_SSL
      sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CCLOUD_API_KEY}" password="${CCLOUD_API_SECRET}";
      ssl-endpoint-identification-algorithm: https
      sasl-mechanism: PLAIN
      dlq-topic-name: "shipment-service-lambda-sink-dlq"
      error-topic-name: "shipment-service-lambda-sink-error"
      spring-json-trusted-packages: "*"
      source-topic-picker-consumer-group-id: "source-topic-picker-consumer-group"
      dlq-consumer-group-id: "dlq-topic-drain-consumer-group"
      error-drain-enabled: true
      dlq-drain-enabled: false

lambda:
  function-name: "shipment-process-dev-index"
  region: "eu-west-1"

endpoints.jmx.enabled: true
spring.jmx.enabled: true

metrics.kafka:
  consumer.enabled: true
  producer.enabled: true