spring:
  kafka:
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: 127.0.0.1:9092
      # The total bytes of memory the producer can use to buffer records waiting to be sent to the server.
      # If records are sent faster than they can be delivered to the server the producer will block for max.block.ms after which it will throw an exception.
      buffer-memory: 33554432
      # Linger up to 100 ms before sending batch if size not met
      linger-ms: 100
      # Batch up to 64K buffer sizes.
      batch-size: 65536
      # Ensure that messages always get delivered, in the right order and without duplicates.
      enable-idempotence: true
      retries: 10000000 # Max retries
      request-timeout-ms: 30000
      retry-backoff-ms: 100

kafka:
  producer:
    retries: 0
    topic-name: shipment-service