spring:
  kafka:
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrap-servers: 127.0.0.1:9092
      # The total bytes of memory the producer can use to buffer records waiting to be sent to the server.
      # If records are sent faster than they can be delivered to the server the producer will block for max.block.ms after which it will throw an exception.
      buffer-memory: 33554432
      # Linger up to 100 ms before sending batch if size not met
      linger-ms: 100
      # Batch up to 64K buffer sizes.
      batch-size: 65536
      # Ensure that messages always get delivered, in the right order and without duplicates.
      enable-idempotence: true
      retries: 10000000 # Max retries
      request-timeout-ms: 30000
      retry-backoff-ms: 100

kafka:
  avro:
    producer:
      schema-registry-url: http://127.0.0.1:8081
      auto-register-schemas: false
      use-latest-version: false
      topic-name: test-topic
      transaction-id-prefix: sionsmith
      value-subject-name-strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy